# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HEU7M6S9D0bxk2qYWpxV1tTXG4vjQSy
"""

# app.py

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd

# Create FastAPI instance
app = FastAPI()

# Load the trained model (XGBoost)
model = joblib.load('xgb_fraud_model.pkl')  # or 'lgbm_fraud_model.pkl'

# Define input data schema
class TransactionData(BaseModel):
    amount: float
    source_encoded: int

# Health check route
@app.get("/")
async def root():
    return {"message": "Fraud Detection Model is up and running!"}

# Prediction route
@app.post("/predict")
async def predict(data: TransactionData):
    input_data = pd.DataFrame([data.dict()])
    prediction = model.predict(input_data)
    return {"fraud_prediction": int(prediction[0])}